<?php

namespace Platform\PlatformBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;
/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
    public function getApplicationsWithAdvert($limit){
        $queryBuilder = $this
            ->createQueryBuilder('a');

        $queryBuilder
            ->innerJoin('a.advert','d')
            ->addSelect('d');

        $queryBuilder->setMaxResults($limit);

        return $queryBuilder->getQuery()->getResult();
    }
}
