hello_homepage:
    path:     /
    defaults: { _controller: SqliSaadPlatformBundle:Advert:index }

hello_id:
    path:     /{id}
    defaults: { _controller: SqliSaadPlatformBundle:Advert:view }

hello_add:
    path:     /add
    defaults: { _controller: SqliSaadPlatformBundle:Advert:add }

hello_slug:
    path:     /{year}/{slug}.{format}
    defaults: 
        _controller: SqliSaadPlatformBundle:Advert:slug 
        _format:    xml
    requirements: 
        year: \d{4}
        format: html|xml
