app:
    resource: '@AppBundle/Controller/'
    type: annotation

Platform:
    resource: "@PlatformPlatformBundle/Resources/config/routing.yml"
    prefix: /Platform

login:
    path: /login
    defaults:
        _controller: OCUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout