platform_platform_homepage:
    path:     /{page}
    defaults: 
        _controller: PlatformPlatformBundle:Platform:index
        page: 1
    requirements:
        page: \d*

platform_annonce:
    path:     /annonce/{id}
    defaults: { _controller: PlatformPlatformBundle:Platform:view }
    requirements:
        id: \d*

platform_add:
    path:     /add
    defaults: { _controller: PlatformPlatformBundle:Platform:add }

Platform_edit:
    path:     /edit/{id}
    defaults: { _controller: PlatformPlatformBundle:Platform:edit }
    requirements:
        id: \d*

Platform_delete:
    path:     /delete/{id}
    defaults: { _contoller: PlatformPlatformBundle:Platform:delete }
    requirements:
        id: \d*

Platform_test:
    path:     /test
    defaults: { _controller: PlatformPlatformBundle:Platform:test }

test:
    path:     /testing
    defaults: { _controller: PlatformPlatformBundle:TestController:index }
