services:
    platform_platform.antispam:
        class: Platform\PlatformBundle\Antispam\PlatformAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50

    platform_platform.application_mailer:
        class: Platform\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    platform_platform.application_listener:
        class: Platform\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@platform_platform.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }
